name: Update fintechs_arg Table

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 min
  workflow_dispatch:

jobs:
  update-fintechs:
    runs-on: ubuntu-latest

    steps:
    - name: Update Lemoncash Rate
      env:
        SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        echo "🔄 Actualizando Lemoncash..."
        
        # Obtener el precio de Lemoncash
        RATE=$(curl -s https://criptoya.com/api/exchanges | jq '.lemoncash.bid')
        echo "💰 Precio obtenido: $RATE"
        
        # Actualizar en Supabase
        RESPONSE=$(curl -X PATCH "${SUPABASE_URL}/rest/v1/fintechs_arg?uuid=eq.lemoncash" \
          -H "apikey: ${SUPABASE_KEY}" \
          -H "Authorization: Bearer ${SUPABASE_KEY}" \
          -H "Content-Type: application/json" \
          -d "{\"rate\":${RATE}}" \
          -w "\nStatus: %{http_code}")
        
        echo "📝 Respuesta: $RESPONSE"