name: Update fintechs_arg Table

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 min
  workflow_dispatch:

jobs:
  update-fintechs:
    runs-on: ubuntu-latest

    steps:
    - name: Update Lemoncash Rate
      env:
        SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        echo "🔄 Actualizando Lemoncash..."
        
        # Obtener el precio de Lemoncash
        RESPONSE=$(curl -s 'https://criptoya.com/api/lemoncash/USDC/ARS/1')
        RATE=$(echo $RESPONSE | jq '.bid')
        echo "💰 Precio obtenido: $RATE"
        
        # Actualizar en Supabase
        curl -X PATCH "${SUPABASE_URL}/rest/v1/fintechs_arg?uuid=eq.lemoncash" \
          -H "apikey: ${{ secrets.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          -d "{\"rate\":${RATE}}"