name: Update fintechs_arg Table

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 min
  workflow_dispatch:

jobs:
  update-fintechs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update fintechs_arg Table in Supabase
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        # Obtener los datos de la API CriptoYa
        response=$(curl -s https://criptoya.com/api/exchanges)
        
        # Filtra solo los exchanges que te interesan
        echo $response | jq '{ 
          exchanges: [
            { uuid: "lemoncash", rate: .lemoncash.bid },
            { uuid: "belo", rate: .belo.bid },
            { uuid: "cocoscrypto", rate: .cocoscrypto.bid },
            { uuid: "takenos", rate: .takenos.bid },
            { uuid: "astropay", rate: .astropay.bid }
          ]
        }' > fintechs.json

        # Itera sobre los exchanges y actualiza la tabla en Supabase
        for row in $(jq -c '.exchanges[]' fintechs.json); do
          UUID=$(echo "$row" | jq -r '.uuid')
          RATE=$(echo "$row" | jq -r '.rate')

          # Inserta o actualiza los datos en la tabla fintechs_arg
          curl -X PATCH "${NEXT_PUBLIC_SUPABASE_URL}/rest/v1/fintechs_arg?uuid=eq.${UUID}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"rate\":${RATE}}"
        done